---
swagger: '2.0'
info:
    version: '0.1.0'
    title: Oberon Plugin API
securityDefinitions:
    NonceAuthorization:
        type: apiKey
        name: X-WP-Nonce
        in: header
paths:
    /v1/subscriptions:
        post:
            tags:
                - Subscriptions
            summary: Updates or Creates a Subscription
            description: Updates a subscription by id or creates new if no id is set
            parameters:
                - in: body
                  name: subscription
                  description: The subscription to create/update.
                  schema:
                      type: object
                      properties:
                          user_id:
                              type: integer
                          status:
                              type: string
                          membership_id:
                              type: string
                          price:
                              type: integer
                          tax_enabled:
                              type: boolean
            responses:
                200:
                    description: Successful response
                    schema:
                        $ref: '#/components/schemas/Subscription'
        get:
            tags:
                - Subscriptions
            summary: Get a subscription by ID or search term (Admin)
            description: Returns a subscription object by its unique ID.
            parameters:
                - name: subscription_id
                  in: query
                  description: The ID of the subscription to retrieve.
                  required: false
                  type: integer
                - name: search
                  in: query
                  description: Search by user or subscription id
                  required: false
                  type: string
            responses:
                200:
                    description: Successful response
                    schema:
                        type: object
                        properties:
                            totalCount:
                                type: integer
                                description: The amount of subscriptions found
                            subscriptions:
                                $ref: '#/components/schemas/Subscription'
                400:
                    description: Bad Request - Invalid ID or query format/empty.
                404:
                    description: Not Found - Subscription with the provided ID does not exist.
                500:
                    description: Subscription search failed
        delete:
            tags:
                - Subscriptions
            summary: Delete a subscription by ID
            description: Allows a subscription to be deleted via an api endpoint by ID
            parameters:
                - name: subscriptionId
                  in: query
                  description: The ID of the subscription
                  required: true
                  type: integer
            responses:
                200:
                    description: Successfully deleted
                    schema:
                        type: boolean
                404:
                    description: No subscription was found/specified
    /v1/transactions:
        post:
            tags:
                - Transactions
            summary: Updates or Creates a Transaction
            parameters:
                - in: body
                  name: transaction
                  description: The transaction to create/update
                  schema:
                      $ref: '#/components/schemas/Transaction'
            responses:
                200:
                    description: Successfully created/updated
                    schema:
                        $ref: '#/components/schemas/Transaction'
        delete:
            tags:
                - Transactions
            summary: Delete a transaction by ID
            description: Allows a transaction to be deleted via an api endpoint by ID
            parameters:
                - name: transactionId
                  in: query
                  description: The ID of the transaction
                  required: true
                  type: integer
            responses:
                200:
                    description: Successfully deleted
                    schema:
                        type: boolean
                404:
                    description: No transaction was found/specified
    /v1/members:
        get:
            tags:
                - Members
            summary: Get a member by search term (Admin)
            description: Returns an array of WP_User object
            parameters:
                - name: search
                  in: query
                  description: The term of the member to retrieve.
                  required: false
                  type: string
            responses:
                200:
                    description: Successful response
                    schema:
                        type: object
                        properties:
                            totalCount:
                                type: integer
                                description: The amount of members found
                            subscriptions:
                                $ref: '#/components/schemas/Member'
                400:
                    description: Bad Request - Invalid ID or query format/empty.
                404:
                    description: Not Found
                500:
                    description: Member search failed

tags:
    - name: Subscriptions
      description: 'Subscription endpoints'
    - name: Transactions
      description: 'Transaction endpoints'
    - name: Members
      description: 'Member endpoints'

components:
    schemas:
        Subscription:
            properties:
                id:
                    type: integer
                user_id:
                    type: integer
                membership_id:
                    type: integer
                coupon_id:
                    type: integer
                period:
                    type: integer
                period_type:
                    type: integer
                renew:
                    type: boolean
                status:
                    type: string
                created_at:
                    type: string
                expires_at:
                    type: string
        Transaction:
            properties:
                id:
                    type: integer
                subscription_id:
                    type: integer
                coupon_id:
                    type: integer
                price:
                    type: integer
                total:
                    type: integer
                tax_amount:
                    type: integer
                tax_rate:
                    type: integer
                tax_class:
                    type: string
                gateway_type:
                    type: string
                prorated:
                    type: boolean
                type:
                    type: string
                renew:
                    type: boolean
                payment_id:
                    type: string
                status:
                    type: string
                created_at:
                    type: string
                expires_at:
                    type: string
        Member:
            properties:
                id:
                    type: integer
